version: 3

tasks:
  start:
    cmds:
      # CGO_CFLAGS_ALLOW="-Xpreprocessor"
      # tip: do `brew reinstall vips` if you run across any error while compiling
      - SECRET=mylocalsecret go run .

  open-file:
    cmds:
      - open "http://localhost:8080/{{ .HASH }}/{{ .PATH }}"
    vars:
      SECRET: 87qxbryf7q3ghncfqw7eohqwe7fhcnoaweihno
      PATH: "{{ .CLI_ARGS | splitArgs | first }}"
      HASH_SCRIPT: |
        const crypto = require('crypto')
        const secret = "{{ .SECRET }}"
        const path = "{{ .PATH }}"
        const hash = crypto.createHmac('sha1', secret)
          .update(path)
          .digest('base64')
          .slice(0, 40)
          .replace(/\+/g, '-').replace(/\//g, '_')
        console.log(hash)
      HASH:
        sh: |
          echo {{ .HASH_SCRIPT | shellQuote }} | node

  podman-buildx:
    cmds:
      - podman buildx build --platform linux/arm64,linux/amd64 . -t blesswinsamuel/media-proxy
