{
 "title": "Media Proxy",
 "description": "Dashboard for media-proxy",
 "tags": [ "media-proxy" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This is a generated dashboard. Any changes made here will be lost on the next generation."
   }
  },
  {
   "title": "Cache Files Count",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 3, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cache_path) (media_proxy_cache_fs_files_count)",
     "legendFormat": "{{cache_path}}"
    }
   ]
  },
  {
   "title": "Cache Files Bytes",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 3, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (cache_path) (media_proxy_cache_fs_size_bytes)",
     "legendFormat": "{{cache_path}}"
    }
   ]
  },
  {
   "title": "Loader Downloaded Bytes",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 3, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(media_proxy_loader_response_size_bytes_sum))",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Vips Memory Usage Bytes",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 11, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(media_proxy_vips_memory_bytes)",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Vips Memory HighWater Bytes",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 11, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(media_proxy_vips_memory_highwater_bytes)",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Vips Memory Alloc Bytes",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 11, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(media_proxy_vips_memory_allocs)",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Vips Memory Files",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 19, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(media_proxy_vips_memory_files)",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Vips Operation Count",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 19, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (operation) (media_proxy_vips_operation_count)",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  { "title": "Go Runtime Metrics", "type": "row", "gridPos": { "x": 0, "y": 27, "h": 1, "w": 24 } },
  {
   "title": "Go Version",
   "type": "stat",
   "gridPos": { "x": 0, "y": 28, "w": 6, "h": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_info{job=\"media-proxy\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Process Start Time",
   "type": "stat",
   "gridPos": { "x": 6, "y": 28, "w": 6, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(process_start_time_seconds{job=\"media-proxy\"}) * 1000",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Process Max File Descriptors",
   "type": "stat",
   "gridPos": { "x": 12, "y": 28, "w": 6, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(process_max_fds{job=\"media-proxy\"})",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Process Virtual Memory Max",
   "type": "stat",
   "gridPos": { "x": 18, "y": 28, "w": 6, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(process_virtual_memory_max_bytes{job=\"media-proxy\"})",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Process Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 31, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(process_open_fds{job=\"media-proxy\"}) by (pod, instance)",
     "legendFormat": "{{pod}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 31, "w": 8, "h": 8 },
   "targets": [
    {
     "expr": "sum(go_threads{job=\"media-proxy\"}) by (pod, instance)",
     "legendFormat": "{{pod}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 31, "w": 8, "h": 8 },
   "targets": [
    {
     "expr": "sum(go_goroutines{job=\"media-proxy\"}) by (pod, instance)",
     "legendFormat": "{{pod}} - {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 39, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"media-proxy\"}[$__rate_interval])) by (pod, instance)",
     "legendFormat": "{{pod}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 39, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"media-proxy\"}) by (pod, instance)",
     "legendFormat": "{{pod}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Go Alloc Rate",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 39, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(go_memstats_alloc_bytes_total{job=\"media-proxy\"}[$__rate_interval])) by (pod, instance)",
     "legendFormat": "{{pod}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Go Alloc Bytes",
   "type": "timeseries",
   "gridPos": { "x": 18, "y": 39, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_alloc_bytes{job=\"media-proxy\"}) by (pod, instance)",
     "legendFormat": "{{pod}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Stack Memory Usage (avg)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 47, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(go_memstats_stack_sys_bytes{job=\"media-proxy\"})",
     "legendFormat": "sys"
    },
    {
     "expr": "avg(go_memstats_stack_inuse_bytes{job=\"media-proxy\"})",
     "legendFormat": "inuse"
    }
   ]
  },
  {
   "title": "Heap Memory Usage (avg)",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 47, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(go_memstats_heap_sys_bytes{job=\"media-proxy\"})",
     "legendFormat": "sys"
    },
    {
     "expr": "avg(go_memstats_heap_idle_bytes{job=\"media-proxy\"})",
     "legendFormat": "idle"
    },
    {
     "expr": "avg(go_memstats_heap_released_bytes{job=\"media-proxy\"})",
     "legendFormat": "released"
    },
    {
     "expr": "avg(go_memstats_heap_inuse_bytes{job=\"media-proxy\"})",
     "legendFormat": "inuse"
    },
    {
     "expr": "avg(go_memstats_heap_alloc_bytes{job=\"media-proxy\"})",
     "legendFormat": "alloc"
    }
   ]
  },
  {
   "title": "Heap Objects",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 47, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(go_memstats_heap_objects{job=\"media-proxy\"}) by (pod, instance)",
     "legendFormat": "{{pod}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Other Memory (avg)",
   "type": "timeseries",
   "gridPos": { "x": 18, "y": 47, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(go_memstats_mspan_sys_bytes{job=\"media-proxy\"})",
     "legendFormat": "mspan_sys"
    },
    {
     "expr": "avg(go_memstats_mspan_inuse_bytes{job=\"media-proxy\"})",
     "legendFormat": "mspan_inuse"
    },
    {
     "expr": "avg(go_memstats_mcache_sys_bytes{job=\"media-proxy\"})",
     "legendFormat": "mcache_sys"
    },
    {
     "expr": "avg(go_memstats_mcache_inuse_bytes{job=\"media-proxy\"})",
     "legendFormat": "mcache_inuse"
    },
    {
     "expr": "avg(go_memstats_buck_hash_sys_bytes{job=\"media-proxy\"})",
     "legendFormat": "buck_hash_sys"
    },
    {
     "expr": "avg(go_memstats_other_sys_bytes{job=\"media-proxy\"})",
     "legendFormat": "other_sys"
    },
    {
     "expr": "avg(go_memstats_gc_sys_bytes{job=\"media-proxy\"})",
     "legendFormat": "gc_sys"
    },
    {
     "expr": "avg(go_memstats_next_gc_bytes{job=\"media-proxy\"})",
     "legendFormat": "next_gc"
    },
    {
     "expr": "avg(go_memstats_sys_bytes{job=\"media-proxy\"})",
     "legendFormat": "sys"
    }
   ]
  },
  {
   "title": "Go GC count",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 55, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(go_gc_duration_seconds_count{job=\"media-proxy\"}[$__interval])) by (pod, instance)",
     "legendFormat": "{{pod}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Go GC Duration Seconds (rate)",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 55, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_sum{job=\"media-proxy\"}[$__rate_interval])) by (pod, instance)",
     "legendFormat": "{{pod}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Go GC Duration Seconds (avg)",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 55, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_sum{job=\"media-proxy\"}[$__rate_interval])) by (pod, instance) / sum(rate(go_gc_duration_seconds_count{job=\"media-proxy\"}[$__rate_interval])) by (pod, instance)",
     "legendFormat": "{{pod}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Lookups rate",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 63, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(go_memstats_lookups_total{job=\"media-proxy\"}[$__rate_interval])) by (pod, instance)",
     "legendFormat": "{{pod}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Mallocs rate",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 63, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(go_memstats_mallocs_total{job=\"media-proxy\"}[$__rate_interval])) by (pod, instance)",
     "legendFormat": "{{pod}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Frees rate",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 63, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(go_memstats_frees_total{job=\"media-proxy\"}[$__rate_interval])) by (pod, instance)",
     "legendFormat": "{{pod}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Process Virtual Memory",
   "type": "timeseries",
   "gridPos": { "x": 18, "y": 63, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(process_virtual_memory_bytes{job=\"media-proxy\"}) by (pod, instance)",
     "legendFormat": "{{pod}} - {{instance}}"
    }
   ]
  }
 ]
}